application:
  name: Aviation-Winners
  project: aviation-winners
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: postgres
routers:
- name: main
  routes:
  - application_name: Aviation-Winners
    paths:
    - /*
